name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: modLoader
    attributes:
      label: Mod Loader
      description: Which Mod Loader are you using?
      options:
        - Fabric
        - NeoForge
        - Synatra Connector
      default: 0
    validations:
      required: true

  - type: input
    id: modVersion
    attributes:
      label: Mod Version
      placeholder: 1.0.0
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What is the bug?
      description: What happened and what did you expect?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste any relevant log output. No need to use backticks.
      render: shell
